spring.application.name=StartYuanReftain

server.port=${StartYuan_SERVER_PORT:8809}

spring.datasource.url=${StartYuan_DB_URL:jdbc:mysql://localhost:3305/startyuan}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=${StartYuan_DB_USERNAME:root}
spring.datasource.password=${StartYuan_DB_PASSWORD:}

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

mybatis-plus.mapper-locations=classpath*:/mapper/**/*.xml
mybatis-plus.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never

